spring:
  application:
    name: emptyframe
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      #是否启用consul
      enabled: true
      discovery:
        #是否启用consul
        enable: true
        register: true
        #健康检查链接
        healthCheckPath: /health
        #监控检查频率
        healthCheckInterval: 15s
        ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${spring.application.instance_id:${server.port}}