#数据源配置
spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/save?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 111111
    hikari: 
      #连接池中允许的最大连接数。缺省值：10,推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
custom:
    datasource:
      names: ds1,ds2
      ds1:
        url: jdbc:mysql://127.0.0.1:3306/save?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 111111
        hikari: 
          #连接池中允许的最大连接数。缺省值：10,推荐的公式：((core_count * 2) + effective_spindle_count)
          maximum-pool-size: 15
      ds2:
        url: jdbc:mysql://127.0.0.1:3306/save?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 111111
        hikari: 
          #连接池中允许的最大连接数。缺省值：10,推荐的公式：((core_count * 2) + effective_spindle_count)
          maximum-pool-size: 15
logging: 
  path: F:/home/log/emptyframe
  file: F:/home/log/emptyframe
  config: classpath:logback-spring.xml
  level: 
    root: info
    hl.king: info
    com.yianit: info
    com.yianit.*.mapper: info