spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    jedis.pool.max-active: 1024
    jedis.pool.max-wait: 10000
    jedis.pool.max-idle: 200
    jedis.pool.min-idle: 0
    timeout: 10000
    block-when-exhausted: true